# This is a basic workflow to help you get started with Actions

name: Sync-To-Gitee

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git checkout -b gitee-bak
          sed -i -e "s#https://github.com/TencentCloudBase/cloudbase-framework/blob/master#https://gitee.com/TencentCloudBase/cloudbase-framework/blob/gitee#g" ./**/*.md
          sed -i -e "s#tdl_anchor=github\&tdl_site=0#tdl_anchor=gitee\&tdl_site=0#g" ./**/*.md  
          sed -i -e "s#https%3A%2F%2Fgithub.com%2FTencentCloudBase%2Fcloudbase-templates#https%3A%2F%2Fgitee.com%2FTencentCloudBase%2Fcloudbase-templates#g" ./**/*.md
          sed -i -e "s#https://github.com/TencentCloudBase/cloudbase-templates/tree/master#https://gitee.com/TencentCloudBase/cloudbase-templates/tree/gitee#g" ./**/*.md
          sed -i -e "s#https://github.com/TencentCloudBase/cloudbase-framework/tree/master#https://gitee.com/TencentCloudBase/cloudbase-framework/tree/gitee#g" ./**/*.md
          sed -i -e "s#https://github.com/TencentCloudBase/cloudbase-framework#https://gitee.com/TencentCloudBase/cloudbase-framework#g" ./**/*.md
          git diff
          
      # Runs a set of commands using the runners shell
      - name: Push to gitee branch
        run: |
          git add .
          git commit -m "doc(readme): use gitee link (generated)"
          git push origin --delete gitee
          git push origin gitee-bak:gitee
